/* Outer Sunset window sign census -- rendering only.
   All data comes from data/data.js, generated by scripts/bundle.py. */

// What the two signs actually say. The full wording is used wherever the sign
// types are introduced; the short form only where a column is too tight for it.
const LABEL = {
  no: "No on G / I \u2665 Sunset Dunes",
  yes: "Yes on G / Open the Great Highway",
  noShort: "No on G",
  yesShort: "Yes on G",
};

const BLOCKS = window.CENSUS.blocks;
const PARK = window.CENSUS.park;

const css = (n) => getComputedStyle(document.documentElement).getPropertyValue(n).trim();
const fmt = (n) => n.toLocaleString("en-US");
const pct = (a, b) => (b ? Math.round((a / b) * 100) : 0);

/* ---------- classification ---------------------------------------------- */

// A block counts toward the totals once. Blocks the walker treated as one
// observation spanning two city blocks are drawn twice but tallied once.
const surveyed = BLOCKS.filter((b) => b.yes !== null);
const withHomes = BLOCKS.filter((b) => b.status !== "no residences");
const tallied = BLOCKS.filter((b) => b.status === "counted");

const TOTAL_NO = tallied.reduce((s, b) => s + b.no, 0);
const TOTAL_YES = tallied.reduce((s, b) => s + b.yes, 0);
const TOTAL = TOTAL_NO + TOTAL_YES;

function side(b) {
  // A block with no buildings can't hold a sign. That's a complete answer, not
  // a gap, so it's kept out of every denominator and drawn differently.
  if (b.status === "no residences") return "nohomes";
  if (b.yes === null) return "unsurveyed";
  if (b.no + b.yes === 0) return "empty";
  if (b.no > b.yes) return "no";
  if (b.yes > b.no) return "yes";
  return "tie";
}

// How many homes on the block are showing a sign drives both the thickness and
// the depth of colour, on a wide enough range that one home cannot read as five.
// Bins were chosen from the actual spread: 31 blocks have 1 such home, 35 have
// 2-3, 15 have 4-6, 5 have 7 or more.
const BINS = [
  { max: 1, weight: 3, step: 1, label: "1" },
  { max: 3, weight: 6, step: 2, label: "2\u20133" },
  { max: 6, weight: 9, step: 3, label: "4\u20136" },
  { max: Infinity, weight: 12, step: 4, label: "7+" },
];
const binFor = (total) => BINS.find((b) => total <= b.max);

function strokeFor(b) {
  const s = side(b);
  if (s === "nohomes") return { color: css("--none"), weight: 2.5, dash: "1 5", op: 1 };
  if (s === "unsurveyed") return { color: css("--unsurveyed"), weight: 2.5, dash: "3 4", op: 0.9 };
  if (s === "empty") return { color: css("--none"), weight: 2.5, dash: null, op: 1 };
  const bin = binFor(b.no + b.yes);
  if (s === "tie") return { color: css("--tie"), weight: bin.weight, dash: null, op: 1 };
  return { color: css(`--${s}-${bin.step}`), weight: bin.weight, dash: null, op: 1 };
}

/* ---------- headline ----------------------------------------------------- */

document.getElementById("bigstat").innerHTML = `
  <div class="bigbar">
    <div class="bb-no" style="flex:${TOTAL_NO}">
      <img class="barlogo" src="assets/no-on-g.svg" alt="${LABEL.no}"
           onerror="this.remove()">
      <span class="barnum"><b>${fmt(TOTAL_NO)}</b><i>${pct(TOTAL_NO, TOTAL)}%</i></span>
    </div>
    <div class="bb-yes" style="flex:${TOTAL_YES}">
      <span class="barnum"><b>${fmt(TOTAL_YES)}</b><i>${pct(TOTAL_YES, TOTAL)}%</i></span>
      <img class="barlogo" src="assets/yes-on-g.webp"
           alt="${LABEL.yes}" onerror="this.remove()">
    </div>
  </div>
  <div class="barkey">
    <span><i class="k-no"></i>${LABEL.no}</span>
    <span><i class="k-yes"></i>${LABEL.yes}</span>
  </div>
  <p class="bigcap">${fmt(TOTAL)} homes are showing a sign, across
     ${fmt(tallied.length)} blocks. Homes for keeping Sunset Dunes park outnumber homes for
     Prop G <strong>${(TOTAL_NO / TOTAL_YES).toFixed(1)} to 1</strong>.</p>`;

const leadNo = surveyed.filter((b) => side(b) === "no").length;
const leadYes = surveyed.filter((b) => side(b) === "yes").length;
const anySign = surveyed.filter((b) => b.no + b.yes > 0).length;

document.getElementById("statgrid").innerHTML = [
  [`${leadNo}`, `blocks where No on G led`],
  [`${leadYes}`, `blocks where Yes on G led`],
  [`${pct(leadNo, anySign)}%`, `of blocks with signs leaned No on G`],
  [`${surveyed.length}`, `blocks walked`],
].map(([n, k]) => `<div class="stat"><div class="n">${n}</div><div class="k">${k}</div></div>`).join("");

/* ---------- map ---------------------------------------------------------- */

const MAX_ZOOM = 18;
const map = L.map("map", { scrollWheelZoom: false, zoomSnap: 0.25, maxZoom: MAX_ZOOM });
const dark = matchMedia("(prefers-color-scheme: dark)");

// Basemap: Esri's Light/Dark Gray Canvas. Keyless, already desaturated, and
// split into a base and a separate label layer -- both go in the tile pane so
// the block colours draw over them. CARTO's tiles were dropped here: they now
// stamp "API KEY REQUIRED" across anonymous requests while still returning 200.
const ESRI = "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas";
const ESRI_CREDIT =
  'Tiles &copy; <a href="https://www.esri.com/">Esri</a> &mdash; Esri, HERE, ' +
  'Garmin, &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> ' +
  'contributors';

let tiles = [];
function setTiles() {
  tiles.forEach((t) => map.removeLayer(t));
  const shade = dark.matches ? "Dark" : "Light";
  // Esri's metadata claims zoom 0-23, but both Gray Canvas bases stop having
  // real tiles after z16 and serve a "Map data not yet available" placeholder
  // beyond it. maxNativeZoom stops at the last real level and upscales past it,
  // so zooming further blurs the basemap instead of breaking it.
  const layer = (name, opts) =>
    L.tileLayer(`${ESRI}/World_${shade}_Gray_${name}/MapServer/tile/{z}/{y}/{x}`,
      Object.assign({ maxZoom: MAX_ZOOM, maxNativeZoom: 16 }, opts)).addTo(map);
  tiles = [
    layer("Base", { attribution: ESRI_CREDIT }),
    layer("Reference"),   // street and place labels, drawn over the base
  ];
}
setTiles();

// Sunset Dunes itself, so the thing being voted on is visible.
PARK.forEach((line) =>
  L.polyline(line, { color: css("--park"), weight: 11, opacity: 0.75, lineCap: "butt" }).addTo(map));

const layers = new Map();
const group = L.layerGroup().addTo(map);

function tip(b) {
  if (b.status === "no residences")
    return `<b>${b.label}</b><span class="r">No buildings on this block</span>`;
  if (b.yes === null) return `<b>${b.label}</b><span class="r">Not counted</span>`;
  const row = (cls, name, n) =>
    `<div class="tiprow"><i class="${cls}"></i><span>${name}</span><em>${n}</em></div>`;
  const note = b.note ? `<span class="r">${b.note}</span>` : "";
  const merged = b.status.startsWith("merged")
    ? `<span class="r">Counted together with the next block</span>` : "";
  return `<b>${b.label}</b>
    ${row("sw-no", LABEL.no, b.no)}${row("sw-yes", LABEL.yes, b.yes)}${note}${merged}`;
}

function drawBlocks() {
  group.clearLayers();
  layers.clear();
  BLOCKS.forEach((b) => {
    const s = strokeFor(b);
    const line = L.polyline(b.coords, {
      color: s.color, weight: s.weight, opacity: s.op,
      dashArray: s.dash, lineCap: "round",
    });
    line.bindTooltip(tip(b), { className: "blocktip", sticky: true });
    line.on("mouseover", () => line.setStyle({ weight: s.weight * 1.45 + 2 }));
    line.on("mouseout", () => line.setStyle({ weight: s.weight }));
    line.on("click", () => highlightRow(b.key));
    line.addTo(group);
    layers.set(b.key, { line, s });
  });
}

drawBlocks();
map.fitBounds(L.latLngBounds(BLOCKS.flatMap((b) => b.coords)), { padding: [14, 14] });
dark.addEventListener("change", () => { setTiles(); drawBlocks(); });

// Esri's label layer doesn't name the cross streets at this zoom, so draw them
// ourselves down the inland edge of the strip, clear of the coloured blocks.
{
  const eastEnd = new Map();
  BLOCKS.filter((b) => b.axis === "ew" && b.street !== "Cutler Ave").forEach((b) => {
    const pt = b.coords.reduce((m, c) => (c[1] > m[1] ? c : m));
    const cur = eastEnd.get(b.street);
    if (!cur || pt[1] > cur[1]) eastEnd.set(b.street, pt);
  });
  eastEnd.forEach((pt, name) => {
    L.marker(pt, {
      interactive: false, keyboard: false,
      icon: L.divIcon({
        className: "xlabel",
        html: name.replace(/ (St|Way|Blvd|Ave)$/, ""),
        iconSize: [0, 0],
      }),
    }).addTo(map);
  });
}

// Only key the categories that actually appear, so a legend entry never
// describes something the map doesn't show.
const present = new Set(BLOCKS.map(side));
document.getElementById("legend").innerHTML = [
  ["no", "--no", `${LABEL.no}`],
  ["yes", "--yes", `${LABEL.yes}`],
  ["tie", "--tie", "Tied"],
  ["empty", "--none", "No signs"],
  ["unsurveyed", "--unsurveyed", "Not counted", [3, 4]],
].filter(([key]) => key === "park" || present.has(key))
 .map(([, v, label, dash]) => {
  // Dotted and dashed keys are drawn as repeating gradients so each swatch
  // matches the line it stands for.
  const fill = dash
    ? `repeating-linear-gradient(90deg, ${css(v)} 0 ${dash[0]}px,` +
      ` transparent ${dash[0]}px ${dash[0] + dash[1]}px)`
    : css(v);
  return `<span><i style="background:${fill}"></i>${label}</span>`;
}).join("");

// The thickness scale, drawn at the real line weights so it reads as a key.
document.getElementById("scale").innerHTML =
  `<b>Homes showing a sign</b>` + BINS.map((bin) =>
    `<span><i style="background:${css(`--no-${bin.step}`)};height:${bin.weight}px"></i>${bin.label}</span>`
  ).join("");

/* ---------- by street ---------------------------------------------------- */

const streets = new Map();
BLOCKS.forEach((b) => {
  if (!streets.has(b.street)) {
    streets.set(b.street, { name: b.street, axis: b.axis, blocks: [],
                            yes: 0, no: 0, walked: 0, homes: 0 });
  }
  const s = streets.get(b.street);
  s.blocks.push(b);
  if (b.status === "counted") { s.yes += b.yes; s.no += b.no; }
  if (b.yes !== null) s.walked++;
  // Blocks with no buildings aren't walkable, so they're out of the denominator.
  if (b.status !== "no residences") s.homes++;
});

const mean = (b, i) => b.coords.reduce((s, c) => s + c[i], 0) / b.coords.length;
for (const s of streets.values()) {
  // Avenues sort west to east; cross streets sort north to south.
  s.sort = s.axis === "ns"
    ? mean(s.blocks[0], 1)
    : -s.blocks.reduce((m, b) => m + mean(b, 0), 0) / s.blocks.length;
}

const ordered = [...streets.values()].sort((a, b) => a.sort - b.sort);
const maxTotal = Math.max(...ordered.map((s) => s.yes + s.no));

function streetRow(s) {
  const total = s.yes + s.no;
  const scale = total / maxTotal;
  return `<div class="srow" data-street="${s.name}">
    <div class="sname">${s.name}<em>${s.walked} of ${s.homes} ${s.homes === 1 ? "block" : "blocks"}</em></div>
    <div class="sbar" style="width:${Math.max(scale * 100, 2)}%">
      <div class="b-no" style="flex:${s.no}"></div>
      <div class="b-yes" style="flex:${s.yes}"></div>
    </div>
    <div class="snum"><b>${s.no}</b> / <i>${s.yes}</i></div>
  </div>`;
}

document.getElementById("streets").innerHTML =
  `<div class="shead">Avenues &mdash; ocean to inland</div>`
  + ordered.filter((s) => s.axis === "ns").map(streetRow).join("")
  + `<div class="shead">Cross streets &mdash; north to south</div>`
  + ordered.filter((s) => s.axis === "ew").map(streetRow).join("");

/* ---------- block table -------------------------------------------------- */

const rows = surveyed
  .slice()
  .sort((a, b) => (b.no + b.yes) - (a.no + a.yes) || b.no - a.no);

document.getElementById("blockcount").textContent =
  `${rows.length} blocks with a count; ${withHomes.length - rows.length} not walked.`;

document.getElementById("blocktable").innerHTML = `
  <thead><tr><th>Block</th>
    <th class="n" title="${LABEL.no}">No on G</th>
    <th class="n" title="${LABEL.yes}">Yes on G</th></tr></thead>
  <tbody>${rows.map((b) => `
    <tr data-key="${b.key}">
      <td>${b.label}${b.note ? ` <span class="tag">${b.note}</span>` : ""}</td>
      <td class="n no">${b.no}</td><td class="n yes">${b.yes}</td>
    </tr>`).join("")}</tbody>`;

function highlightRow(key) {
  document.querySelectorAll("#blocktable tr.on").forEach((t) => t.classList.remove("on"));
  const tr = document.querySelector(`#blocktable tr[data-key="${CSS.escape(key)}"]`);
  if (tr) {
    tr.classList.add("on");
    tr.scrollIntoView({ block: "nearest", behavior: "smooth" });
  }
}

document.getElementById("blocktable").addEventListener("mouseover", (e) => {
  const tr = e.target.closest("tr[data-key]");
  if (!tr) return;
  const hit = layers.get(tr.dataset.key);
  if (hit) hit.line.openTooltip(hit.line.getCenter());
});

document.getElementById("blocktable").addEventListener("click", (e) => {
  const tr = e.target.closest("tr[data-key]");
  if (!tr) return;
  const hit = layers.get(tr.dataset.key);
  if (!hit) return;
  map.fitBounds(hit.line.getBounds(), { maxZoom: 17, padding: [50, 50] });
  hit.line.openTooltip(hit.line.getCenter());
  highlightRow(tr.dataset.key);
});

/* ---------- method ------------------------------------------------------- */

document.getElementById("method").innerHTML = `
  <div>
    <h3>Methodology</h3>
    <p>All signs were counted, tediously, by hand on <b>9 September 2026</b> across
      the Outer Sunset from 45th Avenue west to the ocean. Counts represent dwelling units, not unique signs
      (e.g. a home displaying multiple signs counts once; distinct apartments are counted separately).</p>
  </div>
  </div>`;
