#!/usr/bin/env python3
"""Join geometry + counts into data/data.js, the single file the page loads.

A page that fetch()es local files is blocked under file://, so the data ships
as a script that assigns window.CENSUS. Edit data/counts.csv by hand, rerun
this, and the page picks the changes up on reload.
"""
import csv, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "..", "data")


def num(v):
    return int(v) if str(v).strip() != "" else None


def main():
    counts = {}
    with open(os.path.join(DATA, "counts.csv")) as fh:
        for r in csv.DictReader(fh):
            counts[r["key"]] = r

    blocks, missing = [], []
    for f in json.load(open(os.path.join(DATA, "blocks.geojson")))["features"]:
        p = f["properties"]
        c = counts.get(p["key"])
        if not c:
            missing.append(p["key"])
            continue
        blocks.append({
            "key": p["key"], "street": p["street"], "label": p["label"],
            "axis": p["axis"], "pos": p["pos"],
            "yes": num(c["yes"]), "no": num(c["no"]),
            "status": c["status"], "note": c["note"],
            "coords": [[round(y, 6), round(x, 6)] for x, y in f["geometry"]["coordinates"]],
        })

    park = [[[round(y, 6), round(x, 6)] for x, y in f["geometry"]["coordinates"]]
            for f in json.load(open(os.path.join(DATA, "park.geojson")))["features"]]

    payload = {"blocks": blocks, "park": park}
    out = os.path.join(DATA, "data.js")
    with open(out, "w") as fh:
        fh.write("// Generated by scripts/bundle.py -- edit data/counts.csv instead.\n")
        fh.write("window.CENSUS = ")
        json.dump(payload, fh, separators=(",", ":"))
        fh.write(";\n")

    print(f"data.js: {len(blocks)} blocks, {len(park)} park lines, "
          f"{os.path.getsize(out) / 1024:.0f} KB")
    if missing:
        print("no count row for:", missing)


if __name__ == "__main__":
    main()
